name: Daily Email Scheduler CRON Job

on:
  schedule:
    - cron: '30 13 * * *'

jobs:
  trigger-email:
      runs-on: ubuntu-latest
      container: alpine/curl
      steps:
        - name: Send Daily Email Notifications
          run: curl -X GET https://newsflowservices.vercel.app/api/v1/email/postAllEmails
