name: Daily Email Scheduler CRON Job

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  trigger-email:
      runs-on: ubuntu-latest
      container: alpine/curl
      steps:
        - name: Send Daily Email Notifications
          run: curl -X GET https://newsflowservices.vercel.app/api/v1/email/postAllEmails
        
        - name: Insert Daily Avg in Database
          run: curl -X POST https://newsflowservices.vercel.app/api/v1/news/insertDailyAvg
